import { initialDrivers } from "@/constants/driverData";
import { initialVehicles } from "@/constants/vehicleData";

const today = new Date();
const formatDateTime = (offsetMinutes) => {
  const date = new Date(today.getTime() + offsetMinutes * 60000);
  return `${date.toISOString().slice(0, 16)}`;
};

export const initialTrips = [
  {
    id: 1,
    trip_number: "TRIP-1001",
    vehicle_id: initialVehicles[0].id,
    driver_id: initialDrivers[0].id,
    source: "Mumbai Port",
    destination: "Pune Hub",
    cargo_weight: 9800,
    planned_distance: 160,
    actual_distance: null,
    fuel_used: null,
    revenue: 280000,
    status: "Dispatched",
    departure_time: formatDateTime(90),
    arrival_time: null,
    created_at: formatDateTime(-120),
  },
  {
    id: 2,
    trip_number: "TRIP-1002",
    vehicle_id: initialVehicles[1].id,
    driver_id: initialDrivers[1].id,
    source: "Delhi Yard",
    destination: "Jaipur Depot",
    cargo_weight: 5400,
    planned_distance: 280,
    actual_distance: null,
    fuel_used: null,
    revenue: 412000,
    status: "Draft",
    departure_time: null,
    arrival_time: null,
    created_at: formatDateTime(-30),
  },
  {
    id: 3,
    trip_number: "TRIP-1003",
    vehicle_id: initialVehicles[4].id,
    driver_id: initialDrivers[4].id,
    source: "Bengaluru Hub",
    destination: "Chennai Port",
    cargo_weight: 4200,
    planned_distance: 350,
    actual_distance: 340,
    fuel_used: 48,
    revenue: 585000,
    status: "Completed",
    departure_time: formatDateTime(-720),
    arrival_time: formatDateTime(-660),
    created_at: formatDateTime(-840),
  },
  {
    id: 4,
    trip_number: "TRIP-1004",
    vehicle_id: initialVehicles[5].id,
    driver_id: initialDrivers[5].id,
    source: "Hyderabad Yard",
    destination: "Nagpur Depot",
    cargo_weight: 7600,
    planned_distance: 220,
    actual_distance: null,
    fuel_used: null,
    revenue: 185000,
    status: "Draft",
    departure_time: null,
    arrival_time: null,
    created_at: formatDateTime(-20),
  },
  {
    id: 5,
    trip_number: "TRIP-1005",
    vehicle_id: initialVehicles[6].id,
    driver_id: initialDrivers[6].id,
    source: "Kolkata Terminal",
    destination: "Patna Hub",
    cargo_weight: 6100,
    planned_distance: 310,
    actual_distance: null,
    fuel_used: null,
    revenue: 355000,
    status: "Cancelled",
    departure_time: null,
    arrival_time: null,
    created_at: formatDateTime(-60),
  },
  {
    id: 6,
    trip_number: "TRIP-1006",
    vehicle_id: initialVehicles[8].id,
    driver_id: initialDrivers[8].id,
    source: "Ahmedabad Gate",
    destination: "Surat Port",
    cargo_weight: 4700,
    planned_distance: 190,
    actual_distance: null,
    fuel_used: null,
    revenue: 230000,
    status: "Draft",
    departure_time: null,
    arrival_time: null,
    created_at: formatDateTime(-10),
  },
  {
    id: 7,
    trip_number: "TRIP-1007",
    vehicle_id: initialVehicles[9].id,
    driver_id: initialDrivers[9].id,
    source: "Noida Hub",
    destination: "Lucknow Depot",
    cargo_weight: 7200,
    planned_distance: 360,
    actual_distance: 345,
    fuel_used: 43,
    revenue: 410000,
    status: "Completed",
    departure_time: formatDateTime(-960),
    arrival_time: formatDateTime(-900),
    created_at: formatDateTime(-1020),
  },
  {
    id: 8,
    trip_number: "TRIP-1008",
    vehicle_id: initialVehicles[2].id,
    driver_id: initialDrivers[2].id,
    source: "Vadodara Yard",
    destination: "Indore Hub",
    cargo_weight: 3200,
    planned_distance: 240,
    actual_distance: null,
    fuel_used: null,
    revenue: 200000,
    status: "Draft",
    departure_time: null,
    arrival_time: null,
    created_at: formatDateTime(-5),
  },
];
