export const vehicleStatuses = ["Available", "On Trip", "In Shop", "Retired"];

export const vehicleTypes = ["Truck", "Van", "Mini Truck", "Trailer", "Pickup"];

export const vehicleRegions = ["North", "South", "East", "West", "Central"];

export const initialVehicles = [
  {
    id: 1,
    registration_number: "TRK-104",
    vehicle_name: "Atlas 8x4",
    vehicle_type: "Truck",
    region: "North",
    max_load_capacity: 14000,
    current_odometer: 189200,
    acquisition_cost: 4200000,
    purchase_date: "2022-01-14",
    status: "Available",
  },
  {
    id: 2,
    registration_number: "VAN-208",
    vehicle_name: "Metro Cargo Van",
    vehicle_type: "Van",
    region: "Central",
    max_load_capacity: 6200,
    current_odometer: 132450,
    acquisition_cost: 1850000,
    purchase_date: "2021-08-22",
    status: "On Trip",
  },
  {
    id: 3,
    registration_number: "MTR-312",
    vehicle_name: "City Mini",
    vehicle_type: "Mini Truck",
    region: "South",
    max_load_capacity: 3600,
    current_odometer: 89450,
    acquisition_cost: 1200000,
    purchase_date: "2023-03-10",
    status: "In Shop",
  },
  {
    id: 4,
    registration_number: "TRL-418",
    vehicle_name: "HaulMaster Trailer",
    vehicle_type: "Trailer",
    region: "East",
    max_load_capacity: 22000,
    current_odometer: 243300,
    acquisition_cost: 3100000,
    purchase_date: "2020-11-05",
    status: "Retired",
  },
  {
    id: 5,
    registration_number: "PKP-520",
    vehicle_name: "Harbor Pickup",
    vehicle_type: "Pickup",
    region: "West",
    max_load_capacity: 4800,
    current_odometer: 108900,
    acquisition_cost: 1580000,
    purchase_date: "2022-07-18",
    status: "Available",
  },
  {
    id: 6,
    registration_number: "TRK-611",
    vehicle_name: "Northline 10x4",
    vehicle_type: "Truck",
    region: "North",
    max_load_capacity: 15000,
    current_odometer: 201800,
    acquisition_cost: 4550000,
    purchase_date: "2021-04-12",
    status: "On Trip",
  },
  {
    id: 7,
    registration_number: "VAN-724",
    vehicle_name: "Portside Shuttle",
    vehicle_type: "Van",
    region: "Central",
    max_load_capacity: 6900,
    current_odometer: 146220,
    acquisition_cost: 1960000,
    purchase_date: "2022-09-01",
    status: "Available",
  },
  {
    id: 8,
    registration_number: "MTR-835",
    vehicle_name: "Urban Compact",
    vehicle_type: "Mini Truck",
    region: "South",
    max_load_capacity: 3200,
    current_odometer: 76980,
    acquisition_cost: 1120000,
    purchase_date: "2023-05-30",
    status: "In Shop",
  },
  {
    id: 9,
    registration_number: "PKP-942",
    vehicle_name: "Ridge Pickup",
    vehicle_type: "Pickup",
    region: "West",
    max_load_capacity: 5100,
    current_odometer: 154000,
    acquisition_cost: 1680000,
    purchase_date: "2021-12-03",
    status: "Available",
  },
  {
    id: 10,
    registration_number: "TRK-1030",
    vehicle_name: "Delta 10x4",
    vehicle_type: "Truck",
    region: "East",
    max_load_capacity: 13800,
    current_odometer: 176200,
    acquisition_cost: 4380000,
    purchase_date: "2022-02-17",
    status: "On Trip",
  },
  {
    id: 11,
    registration_number: "VAN-1141",
    vehicle_name: "Express Cargo",
    vehicle_type: "Van",
    region: "Central",
    max_load_capacity: 6700,
    current_odometer: 121800,
    acquisition_cost: 1910000,
    purchase_date: "2020-10-11",
    status: "Retired",
  },
  {
    id: 12,
    registration_number: "TRL-1252",
    vehicle_name: "Long Route Trailer",
    vehicle_type: "Trailer",
    region: "North",
    max_load_capacity: 24000,
    current_odometer: 278950,
    acquisition_cost: 3350000,
    purchase_date: "2019-07-26",
    status: "Available",
  },
];
