import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import Input from "@/components/ui/Input";

const phoneIsValid = (value) => { const local = value.trim().replace(/[\s()-]/g, "").replace(/^(\+91|91)/, ""); return /^[6-9]\d{9}$/.test(local); };
const schema = z.object({ full_name: z.string().trim().min(2, "Full name must be at least 2 characters"), email: z.string().trim().email("Enter a valid email address"), phone: z.string().trim().min(1, "Phone number is required").refine(phoneIsValid, "Enter a valid 10-digit Indian phone number") });
export default function ProfileForm({ user, onSave, isSaving }) { const { register, handleSubmit, reset, formState: { errors } } = useForm({ resolver: zodResolver(schema), defaultValues: { full_name: user.full_name, email: user.email, phone: user.phone } }); useEffect(() => reset({ full_name: user.full_name, email: user.email, phone: user.phone }), [user, reset]); return <section className="border border-slate-200 bg-white p-5 shadow-sm"><div className="border-b border-slate-100 pb-4"><h2 className="text-lg font-semibold text-slate-950">Edit personal details</h2><p className="mt-1 text-sm text-slate-500">Updates apply only to this browser session.</p></div><form onSubmit={handleSubmit(onSave)} className="mt-5 space-y-4"><Input label="Full name" error={errors.full_name?.message} {...register("full_name")} disabled={isSaving} /><Input label="Email" type="email" error={errors.email?.message} {...register("email")} disabled={isSaving} /><Input label="Phone number" type="tel" error={errors.phone?.message} {...register("phone")} disabled={isSaving} placeholder="+91 98765 43210" /><button type="submit" disabled={isSaving} className="bg-cyan-700 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-cyan-800 disabled:cursor-not-allowed disabled:opacity-60">{isSaving ? "Saving…" : "Save profile"}</button></form></section>; }
