"""Database optimization

Revision ID: 36818b532841
Revises: b44b9fc93902
Create Date: 2026-07-12 11:22:03.848312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36818b532841'
down_revision: Union[str, Sequence[str], None] = 'b44b9fc93902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_driver_status', 'drivers', ['status'], unique=False)
    op.create_index('idx_expense_trip', 'expenses', ['trip_id'], unique=False)
    op.create_index('idx_expense_vehicle', 'expenses', ['vehicle_id'], unique=False)
    op.create_index('idx_fuel_trip', 'fuel_logs', ['trip_id'], unique=False)
    op.create_index('idx_fuel_vehicle', 'fuel_logs', ['vehicle_id'], unique=False)
    op.create_index('idx_trip_driver', 'trips', ['driver_id'], unique=False)
    op.create_index('idx_trip_status', 'trips', ['status'], unique=False)
    op.create_index('idx_trip_vehicle', 'trips', ['vehicle_id'], unique=False)
    op.create_index('idx_vehicle_region', 'vehicles', ['region_id'], unique=False)
    op.create_index('idx_vehicle_status', 'vehicles', ['status'], unique=False)
    op.create_index('idx_vehicle_type', 'vehicles', ['vehicle_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vehicle_type', table_name='vehicles')
    op.drop_index('idx_vehicle_status', table_name='vehicles')
    op.drop_index('idx_vehicle_region', table_name='vehicles')
    op.drop_index('idx_trip_vehicle', table_name='trips')
    op.drop_index('idx_trip_status', table_name='trips')
    op.drop_index('idx_trip_driver', table_name='trips')
    op.drop_index('idx_fuel_vehicle', table_name='fuel_logs')
    op.drop_index('idx_fuel_trip', table_name='fuel_logs')
    op.drop_index('idx_expense_vehicle', table_name='expenses')
    op.drop_index('idx_expense_trip', table_name='expenses')
    op.drop_index('idx_driver_status', table_name='drivers')
    # ### end Alembic commands ###
